server:
  port: 8080

spring:
  application:
    name: agendadesesiones
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

management:
  endpoints:
    web: 
      exposure:
        include: health, info

